name: Kali Linux GUI with noVNC (via localhost.run)

on:
  workflow_dispatch:

jobs:
  kali-novnc:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Pull Kali Linux Docker image
        run: docker pull lscr.io/linuxserver/kali-linux:latest

      - name: Run Kali Linux container with noVNC
        run: |
          # Start the Kali Linux container with noVNC on port 3000
          docker run -d \
            --name=kali-linux \
            -e PUID=1000 \
            -e PGID=1000 \
            -e TZ=Etc/UTC \
            -p 3000:3000 \
            -p 3001:3001 \
            --security-opt seccomp=unconfined \
            lscr.io/linuxserver/kali-linux:latest
          
          echo "Container launched. noVNC is running on port 3000."

      - name: Expose noVNC via localhost.run
        run: |
          # Expose the noVNC interface running on port 3000
          ssh -o StrictHostKeyChecking=no -R 80:localhost:3000 localhost.run

      - name: Confirm container is running
        run: docker ps
