name: Run Ubuntu 24.10 in Docker

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  run-ubuntu-container:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Pull Ubuntu 24.10 image
        run: docker pull ubuntu:24.10

      - name: Run command inside Ubuntu 24.10 container
        run: |
          docker run --rm ubuntu:24.10 bash -c "echo 'Hello from Ubuntu 24.10!' && uname -a"
