name: Kali Linux GUI via noVNC

on:
  workflow_dispatch:

jobs:
  kali-novnc:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Pull Kali Linux noVNC Docker image
        run: docker pull lscr.io/linuxserver/kali-linux:latest

      - name: Run Kali Linux container with noVNC
        run: |
          docker run -d \
            --name=kali-linux \
            -e PUID=1000 \
            -e PGID=1000 \
            -e TZ=Etc/UTC \
            -p 3000:3000 \
            -p 3001:3001 \
            --security-opt seccomp=unconfined \
            lscr.io/linuxserver/kali-linux:latest
          
          echo "Container launched. noVNC would be accessible at http://<IP>:3000 on a self-hosted runner."

      - name: Confirm container is running
        run: docker ps
